### ISSUE TITLE
Crash Report -1555951654

### ISSUE THREAD

**Issue by Goober712** [wowsims/cata#836] opened 2024-07-12 02:08 UTC
Link:
https://wowsims.github.io/cata/warlock/demonology/#eJzjUuVgFGB0YMxgLGDsYGScwci4gpHxACPjDUbGF4yMDUyMHUyMG5gYnfgEGD0YI4CKNoDlhBiktrHMYmYLyEmsTC3i4BLgkMrmYhFoe8IMJK/8AJFt00DkDbDIlNuMXGwCp/2UGBmA9NVMEM0u0H2cEcQAKm1mAZJ9Bxi5mAWuBQOZP76DdH17DSI/g02bDSSZBa5kApm3XzIqcXCwGogGsESwaB1l4vrByDBCgZAHtUyyYnBiLQDF7CQmNi4WLiYO1l1MQrrGxkZgYGBkCAIGhoeYRDgenGYSuH6aSeHxaSaNm0+ZHP5eYjrBxHmBifsWE8MjJiYJxhdMKR+YpjE2MkOMtnRYCGE1hDl0MTMonWHihHDTHAQhKuwcJGfNBIGT9pYQkQv2imlgcM3e8ewZEHhjbzSZSSFCglWLxtGt0elAivKGlOMkqacEQAJn73sHRwj/h30CIwDZtmRy

RNG Seed: 3195539240

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 29 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.12/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/cata/sim/core.runSim.func1()
	/home/runner/work/cata/cata/sim/core/sim.go:124 +0x10
panic({0x13ff60, 0x1d04020})
	/opt/hostedtoolcache/go/1.21.12/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/cata/sim/warlock.(*Warlock).registerImpendingDoom.func1(0x3336820, 0x38938c0, 0x38d4c80)
	/home/runner/work/cata/cata/sim/warlock/talents_demonology.go:123 +0xd
github.com/wowsims/cata/sim/core.(*auraTracker).OnCastComplete(0x38f2490, 0x38938c0, 0x38d4c80)
	/home/runner/work/cata/cata/sim/core/aura.go:792 +0x9
github.com/wowsims/cata/sim/core.(*Unit).RegisterSpell.(*Spell).makeCastFunc.func6.1(0x38938c0, 0x3900000)
	/home/runner/work/cata/cata/sim/core/cast.go:173 +0x1f
github.com/wowsims/cata/sim/core.(*Environment).initialize.(*Character).initialize.func1(0x38938c0)
	/home/runner/work/cata/cata/sim/core/character.go:428 +0x9
github.com/wowsims/cata/sim/core.(*Simulation).Step(0x38938c0)
	/home/runner/work/cata/cata/sim/core/sim.go:526 +0x25
github.com/wowsims/cata/sim/core.(*Simulation).runPendingActions(...)
	/home/runner/work/cata/cata/sim/core/sim.go:483
github.com/wowsims/cata/sim/core.(*Simulation).runOnce(0x38938c0)
	/home/runner/work/cata/cata/sim/core/sim.go:370 +0...

**Comment by kayla-glick** [comment] 2024-08-17 06:13
Duplicate of https://github.com/wowsims/cata/issues/917

**Closed by kayla-glick** 2024-08-17 06:13 UTC
