### ISSUE TITLE
Crash Report -996641716

### ISSUE THREAD

**Issue by NikolayKertev** [wowsims/cata#593] opened 2024-06-01 07:20 UTC
Link:
https://wowsims.github.io/cata/rogue/assassination/#eJzlkTFoFEEUhve92VzuBiWTJYHNNW4WhCUgzN1Fd0+R3QQEy5Rnl9vbCxYWYmd3KEgSm0CKM1eEJJUIgpVgQJCAnuIJASGJsROEFAcipNhiTXyzC6Y+xMqf4TFv5ntvfubxi3kQEMBtuAuLAE8AngK8ATgAOAJoISwivECY5SZBN6FGmKEVd4Y6LDd3p36/eS9fELniKXBDfPnFzJ+WnXu2pidt5qwCHxafE+a0gY+Ir3TZt2ymblaAj4tkU5fxyWkmMD/mFWeIfeIeUZPjdop2gJ8XnYSZW5M2aKpSiANCHlu2ToimAEN095hdIPw4XYoqiu8nTL4867/+pyc/J2Jq2L9gK5is7RN55oRMbyepe108SBjFt+8Y5+IV1Ty0nA2gfdzW1X5Fwd1EPWjzPMqJOazhvD71HHkM2n8qQw5acVWb1Q5hlI/QqMFEC52xG596vevbeM2bblSbFU+G1YYrG2FJNsql0CtL12vKSjgdVS7Xq5coRm4prHhRmKauG12puzuovUd9F4cPUfuGaMIRRpsse/FWsMw0u4eFNGstBKPZ+Vgw0VlT+uBXs5Ndf3Ih1Z4/Q55Ifb+8ilbNHJr6xzN2loJB8FbUHYj/G2Wf8/pHMJPlsT8PvwG4vKwF

RNG Seed: 0

runtime error: index out of range [4] with length 4
Stack Trace:
goroutine 6 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.10/x64/src/runtime/debug/stack.go:24 +0x6
main.computeStats.func1()
	/home/runner/work/cata/cata/sim/wasm/main.go:49 +0x10
panic({0x1bffa0, 0x3070bd0})
	/opt/hostedtoolcache/go/1.21.10/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/cata/sim/rogue.(*Rogue).registerEviscerate(0x3820000)
	/home/runner/work/cata/cata/sim/rogue/eviscerate.go:49 +0x25
github.com/wowsims/cata/sim/rogue.(*Rogue).Initialize(0x3820000)
	/home/runner/work/cata/cata/sim/rogue/rogue.go:165 +0x10
github.com/wowsims/cata/sim/rogue/assassination.(*AssassinationRogue).Initialize(0x30313d0)
	/home/runner/work/cata/cata/sim/rogue/assassination/assassination.go:31 +0x4
github.com/wowsims/cata/sim/core.(*Environment).initialize(0x33fa360, 0x33ec900, 0x33ecb80)
	/home/runner/work/cata/cata/sim/core/environment.go:141 +0x25
github.com/wowsims/cata/sim/core.NewEnvironment(0x33ec900, 0x33ecb80, 0x1)
	/home/runner/work/cata/cata/sim/core/environment.go:55 +0x4
github.com/wowsims/cata/sim/core.ComputeStats(0x3389040)
	/home/runner/work/cata/cata/sim/core/api.go:20 +0x6
main.computeStats({{}, 0x0, 0x0}, {0x33e7770, 0x3, 0...

**Comment by rosenrusinov** [comment] 2024-06-02 13:30
Duplicate of #593

**Closed by rosenrusinov** 2024-06-02 13:30 UTC
