### ISSUE TITLE
Addon Export Incorrect on Reforging

### ISSUE THREAD

**Issue by justmuddgaming** [wowsims/cata#515] opened 2024-05-24 05:41 UTC
**Describe the bug**
I used the addon to get my gear into the simulator and there may be other mistakes but it messed up the reforge on my pants. Here is the text:

{"talents":"0300000000000000000-2302000000000000000-23203003023022121311","glyphs":{"minor":[{"spellID":57903},{"spellID":57866},{"spellID":57870}],"prime":[{"spellID":63067},{"spellID":63066},{"spellID":56841}],"major":[{"spellID":56833},{"spellID":56857},{"spellID":56829}]},"class":"hunter","unit":"player","race":"Orc","name":"Muddshotts","gear":{"items":[{"id":64710,"gems":[41398,40112],"reforging":166},{"id":57931,"gems":[]},{"id":64712,"gems":[40112],"reforging":154,"enchant":4205},{"id":56315,"gems":[],"reforging":144},{"id":56281,"gems":[52082,52102]},{"id":63479,"gems":[],"reforging":151},{"id":58125,"gems":[52175]},{"id":57916,"gems":[40112]},{"id":58122,"gems":[52142,52102],"reforging":154},{"id":62385,"gems":[52082],"reforging":166,"enchant":4076},{"id":62348,"gems":[],"reforging":166},{"id":56310,"gems":[],"reforging":167},{"id":52199,"gems":[],"reforging":137},{"id":63840,"gems":[],"reforging":166},{"id":65168,"gems":[],"reforging":167,"enchant":4227},null,{"id":56376,"gems":[],"reforging":130,"enchant":4176}]},"professions":[{"name":"Engineering","level":525},{"name":"Jewelcrafting","level":476}],"level":85,"spec":"survival","realm":"Whitemane"}

Pants are haste to hit but come through as haste to mastery
![image](https://github.com/wowsims/cata/assets/170700576/9683df6d-360e-418f-b051-0533e6b045b2)
![image](https://github.com/wowsims/cata/assets/170700576/540d51fb-3d64-429f-b43c-7d9e156107b5)

**To Reproduce**
1) Export my gear from game
2) Import to sim

**Expected behavior**
Expect it to copy my gear in correctly with the right reforges

**Sim Links and Screenshots**
(https://wowsims.github.io/cata/hunter/survival/#eJzlVF1oFFcUnnPu7O7dE3VvrkkdL6EmY2vXxdiZ2Q1sg7hjnlL74qO+KWiQqpBmXvQt/iAxVAgqjU1fNIotBaUtFCVtoYjE1FY2RFArhZaiRIpiCaVGpNB7Z3YxNg/+PfYww577ne9859xz7yy9yUFACNuhFwYAjgN8BvA9wE2AuwD9CAMIXyB0ZTl0JxRpqeMNIyy9YeeWPdv6eEag+gaoQYw/Yi5aVv4MkC1+vMRooZh4xJz7rS5Y+RGgjHh8nuWHgBaIn88zNz3zETs4zIjEwwfMUIZB+4fHmWtXh5lFXHx7KRaknBjUaPrcsOEbpZz4cpo595a5TGuYehnx4XTN+VvX+NQ405p7yDi/zcQhEkP/MGd/m4laenXhAnMmW/P7wF3I0WvegBtxc2oIoHAWaRas/6lJ70UzOq0u7IVB8Gg1LRfLVBNHAWUWQjfbznabCzME2JZw/6x40Hj1J2P3KmO4xit6/7X2oOgF87HAUHVEP4Ef+EXfv4hv8NN3UJy6g86RKrYeq2L+aBW9T6pYvjGF4ZUp7L4+hRNoT2LmFlq/40TKAZckJ9QXwLyLKaNSxPhfO1xOabLbg45Ig2llEzqNbpYylGr3V5ciaiauNIFf/tWeC9cF7vfUBHwvIlkD/+CuJhJrLz7JPzzKamApckC+pppIFBbxlMROyxAI/ajTknm1glqUotQVRA7UWMhxW+J6S8W5ukvDFSfHmXQ4aI0G01Rgio7l4trXmmLtefhYTpJKWpk+weQBUHuBIvkB8cBgX59gtKpQ4GnJ36+tVctXuJSDzH6OdYRIb9bX57IrouwIzE20nyexQye6sU92h78rkl0qJF++TargcKYT6pIqHnVg+PEMUpIdsWtzKpX6Gig7WqfK9aqb1qo1tMAoP7UZ9rybUXWtleotel22xEeTjucelyxHxEfBjPFWi0p+pDkl01p6TmtlL47eXiLfU+9SKNfOY5S8WNt+SntJoVmT5uw+DhSjulj94PQdvItb97LkkyqHJ2vepnCQWe4vmI1X/T1hY4I3hUtHPjb2Q+WdBJmstPXEdr2yrv41BqewdaOTKgzgK/1/PMvyh8KXSevfevml8l7FkmF99yBcl6xnK5vhX27H80k=)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Edge
 - Version: Unknown
 
**Additional context**
N/A

**Comment by justmuddgaming** [comment] 2024-05-24 05:54
Shoulders are wrong too:
![image](https://github.com/wowsims/cata/assets/170700576/31e0ea79-bfa5-4cb9-adb7-da52e3b9d571)
![image](https://github.com/wowsims/cata/assets/170700576/2748a0fd-608b-4f74-a276-62b84ae645e3)

**Comment by rosenrusinov** [comment] 2024-05-29 18:56
Duplicate of #530 
You can track the progress of the fix for this with the linked issue.

**Closed by rosenrusinov** 2024-05-29 18:56 UTC
