### ISSUE TITLE
Import from Addon has incorrect spirit value

### ISSUE THREAD

**Issue by robertpenberthy** [wowsims/cata#580] opened 2024-05-30 04:33 UTC
**Describe the bug**
Stat values for the Elemental Shaman are not correct on the sim when I import from the addon.  The sim page shows 1783 spirit, but in game I show I have 1850 spirit.  Not sure what else is off, but that is one thing I noticed.  Everything gear wise looks correct.

**To Reproduce**
Import the following:

`{"talents":"3032023212231101320-2010000000000000000-20302000000000000000","glyphs":{"minor":[{"spellID":58057},{"spellID":58059},{"spellID":62132}],"prime":[{"spellID":55447},{"spellID":55454},{"spellID":101052}],"major":[{"spellID":55448},{"spellID":55456},{"spellID":55449}]},"class":"shaman","unit":"player","race":"Draenei","name":"Elesheymin","gear":{"items":[{"id":59458,"gems":[68780,59479,59480],"enchant":4207},{"id":62434,"gems":[],"reforging":145},{"id":63452,"gems":[52207],"enchant":4200},{"id":56434,"gems":[],"enchant":4115},{"id":56563,"gems":[52207],"reforging":147,"enchant":4063},{"id":56313,"gems":[],"reforging":145,"enchant":2332},{"id":58130,"gems":[52208],"reforging":145,"enchant":4068},{"id":62445,"gems":[52207,52207]},{"id":60316,"gems":[52207,52207],"enchant":4114},{"id":62363,"gems":[52208],"reforging":117,"enchant":4069},{"id":56307,"gems":[]},{"id":56391,"gems":[]},{"id":62047,"gems":[],"reforging":162},{"id":56339,"gems":[],"reforging":162},{"id":57872,"gems":[],"enchant":3834},{"id":55070,"gems":[52207],"enchant":4091},{"id":56350,"gems":[52207],"reforging":145}]},"professions":[{"name":"Engineering","level":525},{"name":"Tailoring","level":525}],"level":85,"spec":"elemental","realm":"Atiesh"}`

**Expected behavior**
For the stats to show the same as in the game to make the best sim outcome and to generate the appropriate stat weights.

**Sim Links and Screenshots**
If applicable, add links to your sim settings or screenshots to help explain your problem.

**Desktop (please complete the following information):**
Windows 11, Edge 125.0.2535.67

**Comment by robertpenberthy** [comment] 2024-05-30 04:35
I think I found the problem.  On my boots I reforged Crit > Haste, but the website shows I reforged Spirit > Haste.  That's where my 67 spirit went.

**Comment by rosenrusinov** [comment] 2024-05-30 05:19
Duplicate of #530 

We are aware of the bug and are working on a fix for the exporter

**Closed** 2024-05-30 05:19 UTC
