### ISSUE TITLE
Stat weight sim for demo lock not calculating mastery

### ISSUE THREAD

**Issue by Kvit96** [wowsims/cata#544] opened 2024-05-27 14:47 UTC
mastery being put to a weight off 0 when simming stat weights for demo lock.

**Comment by Tharre** [comment] 2024-05-27 15:57
This is working as intended. The reason this happens is that the demonology and affliction mastery total percentage is rounded down, and statweights are calculated by simming +-40 of that stat. So there are many points where adding or removing 40 mastery does literally nothing for your DPS.

We may change how this works in the future if Blizzard confirms they won't fix this mechanic: https://github.com/JamminL/cata-classic-bugs/issues/1256

**Closed by Tharre** 2024-05-27 15:57 UTC
Labels: invalid, Warlock
