### ISSUE TITLE
Crash Report -1995552824

### ISSUE THREAD

**Issue by sandreid** [wowsims/cata#299] opened 2024-05-02 09:49 UTC
Link:
https://wowsims.github.io/cata/shaman/elemental/#eJztll9sFEUcx3dmdu9mp1W3Q1vWDcJ2U8l5ScPdXkigD70rPlj/PDThBRMfIAhSY7ShD0af7jSBQlH0SOzd+SeURjTRByRS4FCBclzF1qbHgyIhGqrGKpI2VRN7xNaZ3ds99rL+I/GNebh89vv7zG/vZmd3j9yLgQISYAfoBf0AZAB4F4AzAFwCYAaAJAT9EByBYEMQM4kdUkE7TXMo0P3Ulue27cRICWrnALlLOXgCqbO6EXg/K14fRCSoTP+AQq8CUq9cmUXqjG6gWSseP47UpM4mfMniXWwCi/dlEPMWWGWoxQBC6FmiKL+w8oBuiKwshHK8z8cFZNm8T4MysU9UX7anLwwiNqVeSZ5E6uIqw2oXVCaKKPQSIKLSfwOxz2++459jRUSIsv8PpJbv4d9OYOLSLGInNTCWIk3d4iYxfB6SV6Bwe3gGjfzXGe3CBtgL5sFKbQVRMaSNYcy2C1KhDhKoC3XDTWAz23p5uDwWiZkRM2ZGTTMWjUaijNrMNnMUtuJTBah8WIDqmQLUzxZg6LPvYSRfgOtufA0TCxdhV/ki/BSKUxBfhsI0HLhDRWQZwVqAiDi3VzSCRCKoLdZHGkhAEwlUGypRtI+KGmwXqKwFNRbgPc00W6e9VkdOy/QjmZyUtRGZHIZ0GBL5KOD9PjgWcHD4oIvvDbr41kAVS5KD+SkX3xlzcanoYrmKc1VMV/HFEy4OZySyPNyEA1QetYJvvwrwH0tgNOItXP2rwuh4tdAcbqwW3i5JfCUIWOvND4y5uafRj0XJbmRGyGraevMycU+kct4JKifsu9nja+jxWODn8QX2eCzw8/jqezwW+HolqcYrSX4ev24ejwV+Hr+oHo8Ffh6/4h5vqejrlWu9sr83V+vN+XvpWi/t7/Fd5vFY4HvdMjUeC1zvBUSXnBtGuXYekQe1B0iUrnEmHxoXHUwVRE8frrt9aFhhBfiQoGHCsqgZ6WM3o3b7ZvwXN6NZApUn4NBuWKHFlGSTcuyqWKERl4ZcOuRS/rJDp1zKfeJQcsSh1GGHJt9w6KxL/a87tMulIwuoQtPHHeLvZZuuXXEolWWvcevZPNlM27V1ZA1tI/UGIfgosFNSZ8gkaPKD/SuIEr4TS9aesVd0rWYXaIu2ylpEttOeZE9/PN+hA3sRTUuZ76CrtVaiUdXSJB/N2nJpRHVtJWkKL8OA4lHrSxSgray3Ov3U4b5PDqAZ+HgK2a/C1sRQhR5N7EWCsRvJ1lFye6LBzhsTd+eyfFyIr7eTqXjLdmt8Ee/8fIKPn+PmJOz97U34PH2kZ+sO/eGep5/QQ13bdj7Ts/U+faOKw//z35bQnsStTEteKPzDvI1/V//10mCm81bOy4e1mHgadGZB+rHF+8vXz8UrvX6PJwH4E1QWrUE=

RNG Seed: 0

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 6 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.9/x64/src/runtime/debug/stack.go:24 +0x6
main.computeStats.func1()
	/home/runner/work/cata...

**Comment by rosenrusinov** [comment] 2024-05-02 10:08
Duplicate of #298

**Closed by rosenrusinov** 2024-05-02 10:08 UTC
