### ISSUE TITLE
Fireball Glyph

### ISSUE THREAD

**Issue by Muffinman1701** [wowsims/cata#1005] opened 2024-09-12 11:34 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Sim Links and Screenshots**
If applicable, add links to your sim settings or screenshots to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Muffinman1701** [comment] 2024-09-12 11:35
Glyph of Fireball has 5% damage instead of 5% crit for mage

**Comment by hillerstorm** [comment] 2024-09-12 12:12
I think it should actually be 5% crit, it's just that the tooltip was never updated to reflect this. Right @1337LutZ ?

**Comment by 1337LutZ** [comment] 2024-09-12 12:33
@hillerstorm correct. It's because we use the glyph ID in the UI which has the outdated tooltip. The spell ID linked to it does have the correct description 👍

**Comment by hillerstorm** [comment] 2024-09-12 12:48
Closing this since it's working as intended

**Closed by hillerstorm** 2024-09-12 12:48 UTC
Labels: invalid, wontfix
