### ISSUE TITLE
Missing Hit rating

### ISSUE THREAD

**Issue by Neerland** [wowsims/cata#604] opened 2024-06-03 07:09 UTC
**Describe the bug**
Hit rating value seem to be incorrect for Elemental shaman.
I have taken in to account Dranei ofc =)

**To Reproduce**
Generate Data for elemental sham with WowSimsExporter Vv2.11.0 (Equipped Only)
Import to: https://wowsims.github.io/cata/shaman/elemental/#

**Sim Links and Screenshots**
https://imgur.com/a/46YPpSF

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Firefox and Crome

**Comment by rosenrusinov** [comment] 2024-06-03 09:51
@Neerland can you check if your reforges are imported correctly on the sim? Blizzard has not enabled any public API yet for us to see what reforges you have on your gear so we have to parse and guess based on tooltips which does not work all the time.

**Comment by rosenrusinov** [comment] 2024-06-03 20:10
A new version of the WowSimsExporter has been released which should take care of any wrong exports. Can you please try again with the new version if it works as expected @Neerland

**Comment by InDebt** [comment] 2024-06-04 12:10
Could also be related to todays hotfix.

> Fixed a problem with Precision where it was granting an unintended additional 1/2/3% chance to hit.

https://www.wowhead.com/blue-tracker/topic/eu/cataclysm-classic-hotfixes-3-june-510644

**Comment by kayla-glick** [comment] 2024-06-09 03:34
Duplicate of https://github.com/wowsims/cata/issues/628

This is likely due to the Elemental Precision bug or a missing imported reforge. I main Ele and can confirm what I see in the sim reflects in-game stats after verifying reforges

**Closed by kayla-glick** 2024-06-09 03:34 UTC
