### ISSUE TITLE
Crash Report 977751804

### ISSUE THREAD

**Issue by GeorgeCrecoukias** [wowsims/cata#899] opened 2024-08-02 00:10 UTC
Link:
https://wowsims.github.io/cata/warlock/affliction/#eJzlVV1oHFUUnnPvzO7sCTWTm6Sd3EIzHSqsQ7OdmTWNTa27qSCrL9YXCYpgJVYpSktiH3xLFGpsqwSiJhlQSJ8ESynpSxGrEq2trD9JirU1gWC0uNqUVEGN2FbvzNzZbqvii+KDl4X55jvnfPfMd8/M4s06GFCEx2E3DAKMArwO8C7AWYAKQD+BQQJHCGy9yYASdIukI1GMKfzsioCmtj2x/elHe/W0ofNFQGacO0PNJctOHRpTfxmh2RHAtLE8FYF6Y04EK5ZNl0QkAERj+gNqDlvZobByVgTnW+2UCIaVw4ArjKOCG19rgxLeGsZ3U9Tcb9mqSFHConrjs0+pnXphNFIcCVVeuiwq1kScVKk3fjxFzcut8bbDYUNvHaNx+d5L1H3xN7kAVWP+ayrieys0eyDs7z2hNhD1lzYuCvxrqwA/fx/K2HW65jZvU7vVIQDnJDEBl0H5ny5W+qeUOpWt2u5wwPYRFQkqbxLT9/O+77tu3vXyed8TvzY335bPT5J1+unzxKiUifl5mVhflUn23HniLpTJbVdnSPGZ06R0ZYacIuoUqfuCKAtkUDcpNqHOU6jqkxfA1lGgNs/tw2bJfjuv2hlMo9Z2a66GnjxxHd2Eaa4h1Y9qtWwjprho2myQpJ9rv6YwOkNr6UThsPZn7ByRrJvr6GMqJ50Ke4g/iDm2HjMTEOoNvK8m8GC5Cl+b1hL47DGN3YKZnl27nnxsz/beHhb3Mf4ckejqgCbR4hCw+/i9SJjC7kbtkT29fU+xqh+sagFLnppVn0lSs0lsjkhwCJjHN+A6ZiMukLRUxUwAUjaBQsRJwqyZNyb9Cz7cxLhwgrItfDP6zMVGp0FXGXlA4ZE9Gztc18UWZ5Ug8YfqJlwApOJUY4fr2O28E12WizJTf8zc6PVhg1Ova0z4LClRnHgUbu6xDcgd84bqaHw8/6/LQ7Pv5F3YwdpxtdNyQ5uZgMhBxJVOkwhmZhIi7BzBSwaVdfB2XO84OmWZnaJe2GwBXz1BTB2YHpDYeY6BWg3Kw7C5haucZlGY3hkfC9cDVSJ5TpHpByPTvzyscnmtPYvpt7WI/mZerc0e+4lweWUlfhduYZuv22xWTTabVdFy1oQW3aPwlROkUeRUQ/HD+skgIY+n69X9lDVxlvTw8gGQb0xtZ1feiBsOKlCb/M5FGiVPeyzDkzftGqyrkJ5L5BUYoPFXZ1NxPEb99xf3UcX+hJQgExM7ig1xzh3FlmAsXB8WNsXMVGHtjmidKXR9/FG4Fgv+MLG6Tc35j/8Lss8X/w3Z/p6Tf6sbm3N8qdgV3y8XHobfARv3R0E=

RNG Seed: 1739737065

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 13 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.12/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/cata/sim/core.runSim.func1()
	/home/runner/work/cata/cata/sim/core/sim.go:125 +0x10
panic({0x149ea0, 0x1dacba0})
	/opt/hostedtoolcache/go/1.21.12/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/cata/sim/warlock.(*Warlock).registerSummonDemon.func1(0x30a8ea0, 0x39e4500, 0x39e4628)
	/home/runner/work/cata/cata/sim/warlock/summon_...

**Comment by kayla-glick** [comment] 2024-08-17 06:04
Duplicate of https://github.com/wowsims/cata/issues/927

**Closed by kayla-glick** 2024-08-17 06:04 UTC
Labels: bug, Warlock
