### ISSUE TITLE
Crash Report -439662070

### ISSUE THREAD

**Issue by Yotsutester** [wowsims/cata#317] opened 2024-05-04 01:44 UTC
Link:
https://wowsims.github.io/cata/death_knight/blood/#eJztU09IFGEUn/e+2XX2U+vb0WIdTMYhaVtYmJ2pUC8760mig9DFjkFFhw6il/IQa1RrRuFJdz1YhnY0y0NQHTKoLLIMVjGpkCSTijxEqPmvb2bctUKMhG79LvO93+/93nvf4xtaKoEFxyEO0AyQBIgjNCP0IQwjjCFMIFQVMCiHaqiFOugDGHNyKpGBLCj3fB3EW3Pi8Kmj9VIuo8p3oH52bYkEvqiadyBJFtpJ8DQVWdMioVtYNxemVI3EkzZL2WyXGDirBlNAZXaVawlu4lqCy01A89nsIgm8UTUQ7JCxLp5yUdVErjtMERtfJnrn8ooLcMx2x0Zer4d7r6hZ6hzQrayfc828v0102k2nuL9lJeMPttvTv+ZcfI1rpD72dZA4Jn6RxDShOWxmgQ9bQgWay7rnXS3YqOVLRA/UeGo9J6EVSOgh0lYU/uMXyPrfOiqFKmG/qCAV7qCim6ZhGroeMWyYkYhpRMJmWNfNB7hT6h9FdjmNgc40qpfSGPzwHvXWNJanRtBqH8HqZBoHURxGaRyFd/iCBAgtpJLipaL0KE40ifJTeJ/ekGUT87jKGpz1U68iUgz4tRzqoSQcaZD5XJWCHFKCtEQppnkapZJhG2/3kp+i673ELfdWlHcpZTRfy6W+W7Da18h0ezWJa9PIdkE5xCRRJuMgKE5Lc2+ZoyeXcF19j+7qAzfW9xsVrj66vLE/fsYjKxIo23+9kqP1TKJczLXAbxfke5LaJlEFWVVKnMpemTzNVI4YupMxc5fwjDyFOtHz83bEz07lll4ib1MKMqv5Ni869MtFzKbMfcKs2S2VUfjypnEQ5hC6iPtwDlktZIfPOR4Ysvyrz8na7X4noqpH+4iufr8+oxdaRR0pG0+iFS4zHC095mA0Ght6ZuNz1LiJam3oH//dwQvWZmzxI4//4Du4ka6Xh+pim+lrw1lZdZsvloLMFmOmgxzrB/CE9ko=

RNG Seed: 2945064045

When validating reforging for item 69879, the reforging could not be validated. 153
Stack Trace:
goroutine 6 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.9/x64/src/runtime/debug/stack.go:24 +0x6
main.computeStats.func1()
	/home/runner/work/cata/cata/sim/wasm/main.go:49 +0x10
panic({0x1033e0, 0x3952a30})
	/opt/hostedtoolcache/go/1.21.9/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/cata/sim/core.NewItem({0x110f7, 0x0, 0x1004, {0x0, 0x0, 0x0}, 0x99})
	/home/runner/work/cata/cata/sim/core/database.go:353 +0x30
github.com/wowsims/cata/sim...

**Comment by rosenrusinov** [comment] 2024-05-07 08:29
Can't reproduce any error when opening the link. Must have been fixed in the recent couple of days

**Closed by rosenrusinov** 2024-05-07 08:29 UTC
