### ISSUE TITLE
Adding PVP items (vicious) does not account for extra stats

### ISSUE THREAD

**Issue by NoSkills** [wowsims/cata#568] opened 2024-05-29 15:36 UTC
**Describe the bug**
Equipping two pieces of PVP gear doesn't increase base stats as intended.

**To Reproduce**
1. Equip Vicious Shoulders + Vicious Gloves
2. No gems, no reforges, no nothing
3. Notice that the base stats (Strength or Agi depending on class)
4. Some of the item base stat is lost somewhere

**Expected behavior**
Expected base stat to add up to the upgrades.

**Sim Links and Screenshots**
https://wowsims.github.io/cata/rogue/assassination/#eJzlU01IVFEUfue858ybo+M8L5PNXKnGp8b0wrrvvUb8IeYpJRJEQhuljYHZDxHREFQrCQJr5a5y1y6IoGwRGJG10cLQDKJcBEZDLoqgWrir9zPa6FCWtOvcxX33u9/3nXPP41CDCho4cAxOwxDANYCbAOMArwEWAAYRhhDuIHRQwiV1QY9LYxIfiozIoe6Th88fOaOGtBA3SXJXWHtxX9ZBomCp2vwHWUdp6bxi6TEVRbIbe7BPOQfDAMZtpEWQ/tNg4m8VrVKHNAdVFKOoBglMYTq+9/nU1O4xbBO2bVu2EKZtWpZpCtsyG4WwxKpotIRLsldgT7BefZxH7c00JibzmHo7jemX0ygm8tj8ZRadb7PY9XUWJ1GZwfAcSu/wk5IAYhQ+UUayuhjVw+R+NJo5pnBslVgNT5KmV1LFKEQYah7pURkPNraRb6AKnUgdBQ+5l+bBxgTfQfVMp2ojripMHVu6DpFCaOaKBC6iXvoOrJPvoTbWQnGDuYqgmqsxz4/AopgRVUMM90kB0ESaUekC8kUoILt4IGDb+TZKsc2linI9QmHrp61HTvBqiurlFBkFr44Hk7J/M17JTL6TtvJ6Pw8U5cn4iOIb+4/J5HzJ/Cl2lufoODtaWhp18U6qY7XFqdwnF4h4YckpQ1vYpt8QmgVFvN/zDFGVlxt3iPfSAba/JG2GLC7WcGzKrK5plXkDr6MalizAhbcXd901UTPM4Okg03J5JVTbb9NdWsD+G3IwAb3OFVnS32PEPw0OOFUBHneSI9e9eJptCZCZbO2AH6+y7e6MuPExa93CVE+izBjGfzLAv4r0ZWc9ssH+iTV0B9fl+ycRNO3hZ6c9OC9m++AHOFSnrw==

For simplicity sake, Old gear above.

1666 total agi (438 from gear)

https://wowsims.github.io/cata/rogue/assassination/#eJzlU01IVFEUfue858ybo+M8L5PNXKnGp8b0wrrvvUb8IeYpJRJEQhuljYHZDxHREFQrCQJr5a5y1y6QomxnRNZGC0MxEHMRFA24KIJq4a7ez2ijQ1nSrnMX953vft93zj2PSw0qaODAKTgPQwC3AO4CTAAsACwBDCIMITxA6KCES+qCHpfGJD4UGZFD3WePXz5xQQ1pIW6S5K6wdn9B1kGiYKnaqJuitJKvWXpMRZHsxh7sUy7BMIBxD2kZpP80mPhbRavUIS1CFcUoqkECU5iOH3w1Pb1/HNuEbduWLYRpm5ZlmsK2zEYhLLEuGi3hkuw12HOsV5/lUXszg4mpPKbezmD69QyKyTw2f5lD59scdn2dwylUZjG8iNJ7/KQkgBiFz5SRrC5H9TC5H41mjikcWyVWw5Ok6ZVUMQYRhppHelrGg41t5VuoQidSx8BDHqV5sDHB91A906naiKsKU8dXjkOkEJq5IoGLqNe+A+vkB6iNtVDcYK4i6OZmzPMjsChmRNUQw0NSADSRZlS6gHwVCsg+HgjYbr6LUmx7qaJcj1DY+mnrkRO8mqJ6OUXGwOvj8ZTsn0xUMpPvpZ283q8DRXUyPqL4xv5lMjlf8u4cu8hzdJqdLG2Nungn1bHa4lLulQtEvLLilKEdbNtvCM2CIt7veYmoyquDO8Z76Qg7XFI2QxYXGzg2Zdb3tM68gddRDUsW4MLdi6fumqgZZvB0UGm1vRKq7Y/pIS1h/x05eAG9zg1Z0j9gxM8GB5yqAI87yZHbXrzItgTIbLZ2wI/5bLv7Rtz4mLVGMdWTKDOG8Z884F9F+rqzGdlg/+QGuqOb8v2TCIb25LPTHuTL2T74AZ0Ap2g=

Vicious:
1727 total agi (496 from gear)

The gear agi difference according to the Sim is: 58 agi (496-438)

In reality the agi difference between the gear is: 
205+233 = 438 (old gear)
248+248+70 = 566 (vicious with set bonus)

Which should be a 128 agi difference.

The same error can be seen with the warrior vicious gear, and probably other classes.

**Comment by rosenrusinov** [comment] 2024-05-29 18:47
Duplicate of #528

**Closed by rosenrusinov** 2024-05-29 18:47 UTC
