### ISSUE TITLE
Crash Report -2088997291

### ISSUE THREAD

**Issue by Bilbo972** [wowsims/cata#923] opened 2024-08-09 16:18 UTC
Link:
https://wowsims.github.io/cata/warlock/affliction/#eJzlUj1oFEEY3ffN3GWdqBkXhDUQbl0QlkBgs1slhbtJdWUquVIhBguLoJXdaXUeCDkkORMEERQlRLlC5BQEtUiUM+Y0oFEIgUi4E4QTsUj8gczcpjKFjWLhY4r3ve/jzWPmE0dMSMQ4hXEUgCvAbeAxsAI0gTyhQKgQhvdLZJFTQ5V2zzK6V1MzLD1y+sS5k2fMDml2r0BYcq3F7JbjpuemeaXMvJsQHfJJlXkTEF1yqcrshuOyB+W2IORkg9nFHs0t+VHxtYybLpVZQfVLEHvlonK7arkwvLNCyrvzzF7NuFxNGNp5n7xRZTvlLW0xqwZK6vKvU0yJXllbfFG2PzIuU2kEl0sNpgJdSgJx+eqeLuvVnaBbKt+3HpXrzn1mf89okcvGNe52min/4AjP8Qmgd4FsiE0Y/yms7J9yGjSGU+N6mYqUFlyQyR/SYBCEQRD4fuj3h2HQr06f4r+iL9ytPSXHXN4g+bZGdrNGzrsN8j7UyF+vUfzzNWUvLNMz4nXqfE/GOqlPbNLoZ5rCeZbEGYivJyx/LC4yw31JWexJhLH4QDJzND40M63xPBpIlHp0eKyNN9HQ4guNT1FwmZycner9x0viXYz/hm1+dOG3vsnjPGrFQ0m9GR3HNmdElc0=

RNG Seed: 469274078

Couldn't find proto field for talent #57, full string: 223222003013321321-0300000000000000000-3300000000000000000
Stack Trace:
goroutine 6 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.12/x64/src/runtime/debug/stack.go:24 +0x6
main.computeStats.func1()
	/home/runner/work/cata/cata/sim/wasm/main.go:57 +0x10
panic({0x1103c0, 0x6fb29580})
	/opt/hostedtoolcache/go/1.21.12/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/cata/sim/core.FillTalentsProto({0x4238a8, 0x979a1600}, {0xc1957f80, 0x3a}, {0x12, 0x13, 0x13})
	/home/runner/work/cata/cata/sim/core/character.go:703 +0x36
github.com/wowsims/cata/sim/warlock.NewWarlock(0x820ea000, 0xc62007e0, 0xba1c5fc0)
	/home/runner/work/cata/cata/sim/warlock/warlock.go:135 +0xe
github.com/wowsims/cata/sim/warlock/affliction.NewAfflictionWarlock(0x820ea000, 0xc62007e0)
	/home/runner/work/cata/cata/sim/warlock/affliction/affliction.go:31 +0x14
github.com/wowsims/cata/sim/warlock/affliction.RegisterAfflictionWarlock.func1(0x820ea000, 0xc62007e0)
	/home/runner/work/cata/cata/sim/warlock/affliction/affliction.go:16 +0x2
github.com/wowsims/cata/sim/core.NewAgent(0xb810afc0, 0x0, 0xc62007e0)
	/home/runner/work/cata/cata/sim/core/agent.go:173 +0x24
github.com/wows...

**Comment by Tharre** [comment] 2024-09-05 22:16
Duplicate of #895

**Closed by Tharre** 2024-09-05 22:16 UTC
