### ISSUE TITLE
Auto-optimize reforges in Batch mode

### ISSUE THREAD

**Issue by nlybarger** [wowsims/cata#847] opened 2024-07-15 19:04 UTC
**Is your feature request related to a problem? Please describe.**
The batch simulator is not applicable to certain gear situations due to different optimal reforges when a given item is replaced.

**Describe the solution you'd like**
Include an auto-optimize reforge option in the batch simulator.

**Describe alternatives you've considered**
I can do the simulations manually, but this renders the batch simulator useless for many use cases.

**Comment by 1337LutZ** [comment] 2024-07-16 08:45
Duplicate of #834

**Closed by 1337LutZ** 2024-07-16 08:45 UTC
