### ISSUE TITLE
SV Hunter Haste Calculation seems incorrect

### ISSUE THREAD

**Issue by woofdog7777** [wowsims/cata#633] opened 2024-06-07 17:31 UTC
Hunter sim does not calculate haste correctly from gear + talents

Comparing haste on ranged stats ingame vs on sim, it is a little higher in game

**Expected behavior**
Same haste 

**Sim Links and Screenshots**
![image](https://github.com/wowsims/cata/assets/172068421/e82dd24a-2c32-49a3-b92d-acbfb9a158d9)
![image](https://github.com/wowsims/cata/assets/172068421/d36b944f-1698-4f9f-bcc8-0c109ab6cfbe)

I have seen discussion on this topic here in classic hunter discord as I do not understand it myself 

https://discord.com/channels/253213664708919296/1245443448308502558/1245443448308502558

**Comment by ToxicKevinFerm** [comment] 2024-06-09 10:49
I'm aware of this and will fix when I have a few hours to spare. The issue is that in the frontend I just add a flat 3% haste, which is not correct.

**Comment by ToxicKevinFerm** [comment] 2024-06-11 16:27
Should be fixed in #663

**Closed by ToxicKevinFerm** 2024-06-11 16:27 UTC
Labels: bug, Hunter
