### ISSUE TITLE
Mage: Can't click to change items

### ISSUE THREAD

**Issue by markusfiner** [wowsims/cata#496] opened 2024-05-19 17:53 UTC
**Describe the bug**
Nothing happens when i click the items to change them. (Mage in cata)

**To Reproduce**
1. Go to https://wowsims.github.io/cata/mage/fire/
2. Click on an item

Additional info:
After reloading the page a lot of items dissapeared, but i can now click the items and the popup will show.
See screenshot below:
After re-importing the items I can't click again.
![image](https://github.com/wowsims/cata/assets/10339379/f399ddda-81f2-4bba-99cf-d6fd50d2c9c4)

**Expected behavior**
The popup with gear selection should be shown.

**Sim Links and Screenshots**
https://wowsims.github.io/cata/mage/fire/

Import string: 
{"talents":"0000000000000000000000-230330221120121213231-0100000000000000000","glyphs":{"minor":[{"spellID":57924},{"spellID":57928},{"spellID":57925}],"prime":[{"spellID":56382},{"spellID":56384},{"spellID":56368}],"major":[{"spellID":56380},{"spellID":56373},{"spellID":62126}]},"class":"mage","unit":"player","race":"Draenei","name":"Glasscannonx","gear":{"items":[{"id":51281,"gems":[41285,40113],"enchant":3820},{"id":50724,"gems":[40113]},{"id":51155,"gems":[40113],"enchant":3810},{"id":50668,"gems":[40113],"reforging":115,"enchant":3722},{"id":51156,"gems":[40113,40113],"enchant":3832},{"id":50651,"gems":[40113],"enchant":2332},{"id":51159,"gems":[40113],"enchant":3246},{"id":51017,"gems":[40113,40113,40113]},{"id":50694,"gems":[40113,40113,40113],"enchant":3872},{"id":51899,"gems":[40113,40113],"enchant":3826},{"id":50664,"gems":[40113],"enchant":3840},{"id":50398,"gems":[40113],"enchant":3840},{"id":50365,"gems":[]},{"id":50348,"gems":[]},{"id":50608,"gems":[40133],"reforging":117,"enchant":3834},{"id":51922,"gems":[40113]},{"id":50684,"gems":[40152]}]},"professions":[{"name":"Enchanting","level":450},{"name":"Tailoring","level":450}],"level":80,"spec":"fire","realm":"PyrewoodVillage"}

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 124.0.6367.119

**Additional context**

**Comment by Sepulchre49** [comment] 2024-05-19 21:36
This appears to happen after importing the import string provided. While debugging, I discovered that when gear_picker.tsx:588 populates the modal with eligible items, it attempts to compute the EP of gear with random suffixes to determine the ranking of such gear in the modal. In doing so, it calls computeRandomSuffixEP() (player.ts:1140) on items with random suffixes which are not found in the sim.db database, so sim.db.getRandomSuffixById(id) is returning null to computeRandomSuffixEP, which causes an unhandled exception.

Here is the stack trace when I try to click the head slot after importing this string:
```
Uncaught TypeError: can't access property "id", e is undefined
    computeRandomSuffixEP player.ts:1098
    t player.ts:1140
    computeItemEP player.ts:1140
    itemData gear_picker.tsx:588
    setData gear_picker.tsx:579
    openTab gear_picker.tsx:531
    openSelectorModal gear_picker.tsx:366
    e gear_picker.tsx:287
    Tm gear_picker.tsx:294
    promise callback*Tm gear_picker.tsx:284
    o gear_picker.tsx:101
    Nm gear_picker.tsx:101
    buildGearPickers gear_tab.ts:51
    buildTabContent gear_tab.ts:36
    Km gear_tab.ts:32
    addGearTab individual_sim_ui.tsx:407
    tg individual_sim_ui.tsx:320
    D sim.ts:153
    <anonymous> index.html-YM9gjaR_.entry.js:1
2 player.ts:1098:35
    computeRandomSuffixEP player.ts:1098
    t player.ts:1140
    map self-hosted:175
    computeItemEP player.ts:1140
    itemData gear_picker.tsx:588
    map self-hosted:175
    setData gear_picker.tsx:579
    openTab gear_picker.tsx:531
    openSelectorModal gear_picker.tsx:366
    e gear_picker.tsx:287
    (Async: EventListener.handleEvent)
    Tm gear_picker.tsx:294
    (Async: promise callback)
    Tm gear_picker.tsx:284
    o gear_picker.tsx:101
    map self-hosted:175
    Nm gear_picker.tsx:101
    buildGearPickers gear_tab.ts:51
    buildTabContent gear_tab.ts:36
    Km gear_tab.ts:32
    addGearTab individual_sim_ui.tsx:407
    tg individual_sim_ui.tsx:320
    D sim.ts:153
    <anonymous> index.html-YM9gjaR_.entry.js:1
```

This error occurs on multiple item slots with invalid randomSuffix ids. In the head slot, the first one to cause an issue is on the item "Elder's Hat", id 7357, with the very first random suffix option of -84. I suspect there is something about this import string that is causing the gear picker to look at older, unsupported items such as the Elder's Hat, which is an iLvl 34 green that should not be on the list of items.

This error is occurring on the live deployment of the sim as well as my local dev environment.

I am investigating the random suffix and database code to see if I can find the source of the issue; I could use some help understanding how the database is created and shared between the front and back end.

**Comment by Sepulchre49** [comment] 2024-05-22 06:55
After further investigation, I've narrowed down the cause. The import string contains a bunch of WOTLK items that by default do not get built into the client's database. This triggers the client to load the leftovers database, which scrapes a bunch of items from Wowhead with a ton of different random suffixes. While this database is created and loaded, not every random suffix id found on items in the leftovers DB is being added to the set of available random suffix ids.

I will look into this further tomorrow to see if I can find an easy fix for this. However, given that we are now in Cata and questing greens are iLvl 287, I believe this issue falls under "prepatch support", which the maintainers have stated they will not support. I will try to correct the bug to ensure that you can still use the app when importing items like this, but there is more urgent work to be done on the sim that may take precedence.

**Comment by markusfiner** [comment] 2024-05-22 07:14
Thanks a bunch for looking in to this, but as you say probably the least important to fix given that we all soon have cata heroic gear. But if it's an easy fix then might as well get it out :)

**Comment by rosenrusinov** [comment] 2024-05-29 18:55
@Sepulchre49 as you've already investigated this do you mind actually fixing this so it doesnt do a NRE but instead just does not add the item? Seems to me like a decent solve for this

**Closed** 2024-05-31 07:52 UTC
