### ISSUE TITLE
Crash Report -1924798912

### ISSUE THREAD

**Issue by BloodyGH** [wowsims/cata#1073] opened 2024-10-03 01:15 UTC
Link:
http://localhost:3333/cata/death_knight/blood/#eJzdlE9IFHEUx+e937g7+9xqHA22IXWaErYFaXa2YvPQjp4kOkh0sFuCGoGH0C51aYuwsL8Q1CpqfyiNArM6FEWHOlRGhcW2qKFEQQUFCZForNZvZnZLcovs2DvM7/2+v+/7vDc/dpaKJQiCBVshDpAAGAc4iNCPMIjwCqFqoQxRqIYdcBNgCKACZVAEtY06mKemqW5XQ7PklUl9CaTIXdMsMK7pnsvt4tdTLNgN5JX3plmwF8gvn+aHbzWdnUgwInk0zQL7teBxu6yH5628bOIUy5SRfIdro5oOAslyJ688pOk2UwheAFLlkRlmnJn55gb8qOy1ad3c3bdstuaXr3PaWKluC3ykgfssmAAS5edpxp9jzrM/bR9NceNFlQRec36K6RmCni+BEaiBWjgOEHqFAUZDIPynocT/8dXGY7nX+UeFUCVsEFUk4RauNyIR0zQNI2wvZiTM13B5xJgb5YYxV76HK6STSZSvpzBwNInakSQGr6XQuJrC6LEkWokXWJ1I4kMUB1EaQeE1TrAAUBFJqodE6cAU6hLxrHyt0fJDvR9nOdSOJ1lv2GhR+PgVglKiLiUlJEuiwkZAUL2UR8w0yhx/Yhpznq/OnN+9wpSwuorKlOVzPGuNMlqg55PvGmQGyg6WExnNIFMzqCxWC8lHXG6sa2ppcOR36dyTrHHL5BdppoTUINkev04kmXbVjT42a9fT545wYExUNLXEYXkU9ijLCpuGym9H+nSbaaD4VXJ2T1vtXalaTIWhAt47rw1RAhtEaLY4wLY+pnCzk09+yMzvvvaXKdGRn/H5bUZBaFG2p0OIzm6ZbeJR8vb9bBJ2mwy/wfdYP4mwl7k/wSLrbCbbYrWxYp+T7ktaBR3tdgzHVj55bAdZmkd/gNXMdcQbrYIsYIlrHYitc5XB2LJGJ1KxSrf4Y8w8jDsufYbd+Zvqttdrm+uatzXs1GoD3tA8/19q9lvz+8Qm9/yNK17/wOZujHZ1Vv6Z8yvv93znNuLnfJXtkL3LDFu0vgMc5AeO

RNG Seed: 1702638567

runtime error: index out of range [-1]
Stack Trace:
goroutine 391 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.13/x64/src/runtime/debug/stack.go:24 +0x5e
github.com/wowsims/cata/sim/core.runSim.func1()
	/home/runner/work/cata/cata/sim/core/sim.go:125 +0x98
panic({0x1b6ff00?, 0xc0003a4978?})
	/opt/hostedtoolcache/go/1.21.13/x64/src/runtime/panic.go:914 +0x21f
github.com/wowsims/cata/sim/core.(*Unit).partialResistRollThresholds(0x9?, 0x1c7f7d0?)
	/home/runner/work/cata/cata/sim/core/spell_resistances.go:165 +0x29b
github.com/wowsims/cata/sim/core.(*Spell).ResistanceMultiplier(0xc70b3bee00?, 0xc70d53fb90?, 0x0?, 0x165a0bc00?)
	/home/runner/work/cata/cata/sim/core/spell_resistances.go:50 +0x192
github.com/wowsims/cata/sim/core.(*SpellResult).applyResistances(0xc70de141b8, 0x13bed37?, 0xc70de23900?, 0x20?, 0xc70b442000?)
	/...

**Comment by 1337LutZ** [comment] 2024-10-17 11:44
Duplicate of https://github.com/wowsims/cata/issues/1081

**Closed by 1337LutZ** 2024-10-17 11:44 UTC
