### ISSUE TITLE
Crash Report -1642695079

### ISSUE THREAD

**Issue by Francoporto** [wowsims/cata#290] opened 2024-05-01 18:08 UTC
Link:
https://wowsims.github.io/cata/hunter/beast_mastery/#eJzjUuVgFGB0YMxgLGDsYGScwci4gpHxACPjDUbGF4yMDUyMHUyMG5gYnXg4GD0gSoBiQgxSd1hnMbMF5CRWphZxsAswSV1n5OIXuNjPLPFSVolt22GmrTuZuDgFTn5iUmIGMXkEzgPlHshCeJwCy7qYIUx+gXNAiR9ATStPMl37z8TFK3C/m1miVU6JBSjNwMUlcKmfGcrmF/gANI9zw04mCOISErgKVPteVokTKA9BQJum9zArsUF5nAIrngCdMP8kiPmoE2gpSB+LwK5OZiB5/CPIAT87mSU+QxwA0sIANOIc0NgZMmAXKjEZMGodZeKawMQwClCAkAGpOqwYnJgKGKuUuRS55AXkpSQ5mAQYDZgsmD2YIxgzmCtAqWsCI9MMRmCQ72KyMTI2NjAyNjA2NDQ2MjA0NAJCXSAfHehiiADBISYejsXnmQSWPGWSmHSe6QQTywUm9ltMDI+YuCQYldiEWLiAEf2CKaWRGeIyC4eFUFakQxczg9ITJk4wryHNQRAiLuIgOWsmCJy0t4SIXLBXTAODa/aOZ8+AwBt7o9VMChESrFo0Ti0anQ7kaGtIOU5AXzBZ5hIDIIG2972DI4T/wz6BEQAXQ4+6

RNG Seed: 241544933

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 15 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.9/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/cata/sim/core.runSim.func1()
	/home/runner/work/cata/cata/sim/core/sim.go:123 +0x10
panic({0x128e60, 0x1a674c0})
	/opt/hostedtoolcache/go/1.21.9/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/cata/sim/hunter.(*Hunter).applyFervorCD.func1(0x2c7cfc0, 0x34ca000, 0x3428d80)
	/home/runner/work/cata/cata/sim/hunter/talents.go:524 +0x5
github.com/wowsims/cata/sim/core.(*Spell).applyEffects(0x3428d80, 0x2c7cfc0, 0x34ca000)
	/home/runner/work/cata/cata/sim/core/spell.go:538 +0x13
github.com/wowsims/cata/sim/core.(*Unit).RegisterSpell.(*Spell).makeCastFunc.func5(0x2c7cfc0, 0x34ca000)
	/home/runner/work/cata/cata/sim/core/cast.go:181 +0x7a
github.com/wowsims/cata/sim...

**Comment by rosenrusinov** [comment] 2024-05-07 10:57
Can't reproduce anymore, should be fixed

**Closed by rosenrusinov** 2024-05-07 10:57 UTC
