### ISSUE TITLE
Crash Report 576647745

### ISSUE THREAD

**Issue by volbiathenewb** [wowsims/cata#894] opened 2024-07-31 06:22 UTC
Link:
https://wowsims.github.io/cata/warlock/demonology/#eJztVE1oHVUUnnPuvPdmTmp6e9O001vwTaYuwqON7wchhtI3CS6CuCilSLeB9MdSqSQV1FXSuoj9gVSlzXu0iwaKGh4SstKAokVtNZW+/v9F4k9jUgg0WBSDjfbO3JmQWjdCxYWezTl855zv3PPdO0OrLfBhB/QBDAC8C/AJwDWAPoRhhLbaILkFXoHhEBWG/I7KLLlxV8erW7usFLfkj0CCf1hlzh3Xsyslc7LKrlYZpXh1ijWeBFrKPzrHnGnXY70DrLEfiPinqvotN0gKfvMKcybSXvLOUTZ3NMw/xi+q/FzaAyMo4fzYFHNupT1T5Q3NOPUe85JzuuOdALihWA67XrJvgCkiWsJ/Uj330h5TgDrK2S9C5iX88Dzz4q4U//hcCKf4xK0QIT48y5y7aZ0dV6f4La2Ct+eDrMf6ATKn0QH6FYz/qIn2R8XUYrTZPRA9qzfRJCRjFOW6QiGXV1bIZgu5bF7FuZzC8tn8KXzC+nYM+dUxdC5NovvDGDZen8TsN5PY/PsF9PdexPb5C3gGzSrW3EDjeywl1F3VkyWTZFqnPjc9m1KUWNfclO2mOkpKNdNZFoH5pqe6F2rL07AYXk4pmSBmnc9FaFahwpTYYogmuZY86VLdCHCqtd5Y4f4RG5BdhoDu9oQpIy82yPW0RjSQPRKmej8z43DfB4k4HBwzRT3Zz+ze/eL2lzu6OoU+1kw/iHpZR/YgRBvFm4n1soVy8smYQEFx+PMs0spMvcWEPRoCZw5B0EZY6I62EsECuia1M4BumtIqm1GknRgCqb6K4yDLQG3Cp7WZTMC5U+lhjaMLcvUIOhYIq4xBxzhKKptxknim1koIfNbQo5Wom8UmasikFUfd6MPS6bJ8NzmZFQ+OUQGxnMr8leJSj9YqafGHDoZkgX9ozwrEe1Z0a+UBgWcOMhn5xYylX1BGXrjycVouBCW+QrQWLvzyAT1TeUFy4U0JW+qH9H7NNHbO4hHoZfpjcP0TOup53t/PDO9Ioh1sDWzzl+maDf6qcimwL4tPa6RabNgW2pVi69dnA5sp5iv40tBdeK1mU8cLne7mjq7tW/e4W5xE5l/+Z2183f8naHs6Ty/mfa75+LHWP9eEavUM2q0l0AJeL0Y1pv+/XH9Lrvvv+jrh

RNG Seed: 650372139

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 11 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.12/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/cata/sim/core.runSim.func1()
	/home/runner/work/cata/cata/sim/core/sim.go:125 +0x10
panic({0x149ea0, 0x1dacba0})
	/opt/hostedtoolcache/go/1.21.12/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/cata/sim/warlock/demonology.(*DemonologyWarlock).registerSummonFelguard.func1(0x337a6c0, 0x330d180, 0x330d2a8)
	/home/runner/work/cata/cata/sim/warlock/demonology/demonology.go:92 +0x6
github.com/wowsims/cata/sim/core.(*Unit).RegisterSpell.(*Spell).makeCastFunc.func6(0x337a6c0, 0x38af500)
	/home/runner/work/cat...

**Comment by kayla-glick** [comment] 2024-08-17 06:05
Duplicate of https://github.com/wowsims/cata/issues/927

**Closed by kayla-glick** 2024-08-17 06:05 UTC
Labels: bug, Warlock
